[package]
name = "staking-bank-static-prod-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.staking-bank-static-prod]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
