[package]
name = "staking-bank-static-module"
version = "0.0.0"
authors = [ "you",]
edition = "2021"

[lib]
path = "src/staking_bank_static_module.rs"


[dependencies.multiversx-sc]
version = "0.50.5"
